@echo off

echo Building backend...
call npm run backend-build

echo Starting backend...
start cmd /k "node "%~dp0dist\backend\index.js""

echo Starting frontend...
start cmd /k "cd /d "%~dp0" && npm run dev"

echo Both frontend and backend are starting...