-- Recriação da tabela PEDIDO com sintaxe SQL compatível
CREATE TABLE PEDIDO (
    PEDIDO VARCHAR(20) NOT NULL,
    CODVEN VARCHAR(10) NULL,
    CODCLI VARCHAR(20) NULL,
    NOMCLI VARCHAR(100) NULL,
    ENDCLI VARCHAR(255) NULL,
    BAICLI VARCHAR(100) NULL,
    CIDCLI VARCHAR(100) NULL,
    ESTCLI VARCHAR(2) NULL,
    BASE DATE NULL,
    RECOL DATE NULL,
    COBRAN DATE NULL,
    TOTPED DECIMAL(18, 2) NULL,
    SITU VARCHAR(10) NULL,
    DATPED DATE NULL,
    RETORNO VARCHAR(20) NULL,
    TOTVEN DECIMAL(18, 2) NULL,
    DATPAG DATE NULL,
    VALPAG DECIMAL(18, 2) NULL,
    RESIDUO DECIMAL(18, 2) NULL,
    COB VARCHAR(10) NULL,
    LIMITE DECIMAL(18, 2) NULL,
    PRIMARY KEY (PEDIDO)
);

-- Recriação da tabela ITEMPEDIDO com sintaxe SQL compatível
CREATE TABLE ITEMPEDIDO (
    PEDIDO VARCHAR(20) NOT NULL,
    CODART VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(255) NULL,
    QTDSAI INT NULL,
    QTDRET INT NULL,
    PRECUS DECIMAL(18, 2) NULL,
    PREVEN DECIMAL(18, 2) NULL,
    QTDANT INT NULL,
    CUSANT DECIMAL(18, 2) NULL,
    VENANT DECIMAL(18, 2) NULL,
    OPER VARCHAR(10) NULL,
    PRIMARY KEY (PEDIDO, CODART),
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDO(PEDIDO) ON DELETE CASCADE
);